import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ChevronDown, ThumbsUp, XCircle } from 'lucide-react';
import { AgentFileOp } from '../types';

interface EditPreviewProps {
  ops: AgentFileOp[];
  isDarkMode: boolean;
  onRejectAll: () => void;
  onKeepAll: () => void;
  messageId: string;
}

/**
 * EditPreview displays a summary of code changes generated by the agent.
 * Shows file counts, line diffs, and action buttons with keyboard shortcuts.
 * Zed-style dark theme with smooth animations.
 */
export const EditPreview: React.FC<EditPreviewProps> = ({
  ops,
  isDarkMode,
  onRejectAll,
  onKeepAll,
  messageId,
}) => {
  const [isExpanded, setIsExpanded] = useState(true);

  if (!ops || ops.length === 0) return null;

  // Calculate line statistics from content (rough estimate)
  const stats = ops.reduce(
    (acc, op) => {
      if (op.type === 'write') {
        const lines = (op.content || '').split('\n').length;
        acc.added += lines;
        acc.files += 1;
      } else if (op.type === 'delete') {
        acc.removed += 1;
        acc.files += 1;
      }
      return acc;
    },
    { added: 0, removed: 0, files: 0 }
  );

  const summaryText = `Edits • ${stats.files} ${stats.files === 1 ? 'file' : 'files'} • +${stats.added} -${stats.removed}`;

  return (
    <motion.div
      initial={{ opacity: 0, y: -8 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -8 }}
      className={`rounded-lg border transition-colors ${
        isDarkMode
          ? 'bg-gray-800/50 border-gray-700/50 text-gray-100'
          : 'bg-gray-50 border-gray-200 text-gray-900'
      } overflow-hidden`}
    >
      {/* Header with summary and expand toggle */}
      <div
        className={`px-3 py-2.5 flex items-center justify-between cursor-pointer hover:opacity-80 transition-opacity ${
          isDarkMode ? 'bg-gray-800/70' : 'bg-gray-100'
        }`}
        onClick={() => setIsExpanded(!isExpanded)}
      >
        <div className="flex items-center gap-2 flex-1 min-w-0">
          <motion.div
            animate={{ rotate: isExpanded ? 0 : -90 }}
            transition={{ duration: 0.2 }}
          >
            <ChevronDown className="w-4 h-4 text-gray-500 shrink-0" />
          </motion.div>
          <span className="text-xs font-medium text-gray-500">{summaryText}</span>
        </div>

        {/* Quick action buttons */}
        <div className="flex items-center gap-1.5 shrink-0 ml-2">
          <button
            onClick={(e) => {
              e.stopPropagation();
              onKeepAll();
            }}
            title="Keep all changes (Alt+Shift+Y)"
            className={`p-1.5 rounded transition-colors ${
              isDarkMode
                ? 'hover:bg-green-900/30 text-green-400 active:bg-green-900/50'
                : 'hover:bg-green-100 text-green-600 active:bg-green-200'
            }`}
          >
            <ThumbsUp className="w-4 h-4" />
          </button>
          <button
            onClick={(e) => {
              e.stopPropagation();
              onRejectAll();
            }}
            title="Reject all changes (Alt+Shift+Z)"
            className={`p-1.5 rounded transition-colors ${
              isDarkMode
                ? 'hover:bg-red-900/30 text-red-400 active:bg-red-900/50'
                : 'hover:bg-red-100 text-red-600 active:bg-red-200'
            }`}
          >
            <XCircle className="w-4 h-4" />
          </button>
        </div>
      </div>

      {/* Expanded file list with line counts */}
      <AnimatePresence>
        {isExpanded && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: 'auto' }}
            exit={{ opacity: 0, height: 0 }}
            transition={{ duration: 0.2 }}
            className={`border-t ${
              isDarkMode ? 'border-gray-700/50' : 'border-gray-200'
            }`}
          >
            <div className="divide-y divide-gray-700/30">
              {ops.map((op) => {
                const lineCount = (op.content || '').split('\n').length;
                const isAdded = op.type === 'write';
                const isDeleted = op.type === 'delete';

                return (
                  <div
                    key={op.path}
                    className={`px-3 py-2 text-xs font-mono flex items-center justify-between gap-2 ${
                      isDarkMode ? 'hover:bg-gray-700/30' : 'hover:bg-gray-100/50'
                    } transition-colors`}
                  >
                    <span
                      className={`truncate ${
                        isDarkMode ? 'text-gray-300' : 'text-gray-700'
                      }`}
                    >
                      {op.path}
                    </span>
                    <div className="flex items-center gap-1.5 shrink-0">
                      {isAdded && (
                        <span className="text-green-500 font-semibold">
                          +{lineCount}
                        </span>
                      )}
                      {isDeleted && (
                        <span className="text-red-500 font-semibold">
                          delete
                        </span>
                      )}
                      {!isAdded && !isDeleted && (
                        <span
                          className={isDarkMode ? 'text-gray-500' : 'text-gray-400'}
                        >
                          —
                        </span>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
};

export default EditPreview;
